alias npmis="npm i --save"
alias npmhq="npm-research -G 5"
alias npmin="npm info"
alias npmls="npm config ls -l"
alias dpskl="docpad skeleton"
alias dpupg="npm i -g docpad"
alias dpcln="docpad clean"
alias dpdep="npm ls"
